cleanup a bit

diff --git a/bin/mac b/bin/mac
--- a/bin/mac
+++ b/bin/mac
@@ -2,7 +2,7 @@
 #
 # MAC Bootstrap Script
 #
-set -u -e
+set -e
 
 #
 # get sudo
@@ -31,119 +31,102 @@ write_log() {
 #
 # install brew
 #
-install_brew() {
-  if ! command -v brew >/dev/null;
+brew_install() {
+  write_log "${FUNCNAME[0]} => init"
+
+  local github_url='https://raw.githubusercontent.com'
+  local brew_install_url="${github_url}/Homebrew/install/master/install"
+
+  # return early if already installed
+  if command -v brew >/dev/null;
   then
-    log "installing homebrew"
-    curl -fsSL \
-      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-  else
-    log "homebrew already installed.. moving on"
+    return 0
   fi
-}
 
-#
-# update brew itself
-#
-update_brew() {
-  brew update
-}
-
-#
-# upgrade installed formulae
-#
-upgrade_formulae() {
-  log "install_taps initializing"
-  brew upgrade --all
-  log "install_taps terminating"
-}
-
-#
-# install a list of taps
-#
-install_taps() {
-  local taps=(
-    'homebrew/php'
-    'caskroom/cask'
-    'homebrew/dupes'
-    'homebrew/versions'
-    'homebrew/completions'
+  # install brew
+  (
+    curl -fsSL "${brew_install_url}" | ruby
   )
 
-  log "install_taps initializing"
-  for tap in "${taps[@]}";
-  do
-    log "tapping ${tap}"
-    brew tap "${tap}"
-  done
-  log "install_taps terminating"
+  write_log "${FUNCNAME[0]} => done"
 }
 
 #
-# install a sh!t ton of bottles
+# brew $action
+# aka: brew upgrade, brew clean
 #
-install_bottles() {
-  local bottles=(
+brew_action() {
+  write_log "${FUNCNAME[0]} => init"
+
+  local brew_act="${1}"
+  local brew_arg="${2}"
+  local brew_cmd=$(which brew)
+  write_log "${FUNCNAME[0]} action => ${brew_act} ${brew_arg}"
+
+  # run specified brew cmd
+  (
+    $brew_cmd $brew_act $brew_arg
+  )
+
+  write_log "${FUNCNAME[0]} => done"
+}
+
+#
+# install brew bottles
+#
+brew_install_bottles() {
+  write_log "${FUNCNAME[0]} => init"
+
+  local brew_bottles=(
+    'ansible'
     'bash'
     'bash-completion2'
+    'fping'
+    'git'
+    'hub'
     'jq'
+    'lua'
     'openssl'
     'shellcheck'
     'subversion'
     'tree'
     'vagrant-completion'
+    'vim'
   )
 
-  log "install_bottles initializing"
-  for bottle in "${bottles[@]}";
-  do
-    log "installing bottle: ${bottle}"
-    brew install "${bottle}"
-  done
-  log "install_bottles terminating"
-}
+  # tap up
+  brew_action "tap" "homebrew/completions"
+  brew_action "tap" "homebrew/versions"
 
-#
-# cleanup brew (outdated formulae)
-#
-cleanup_brew() {
-  brew cleanup
-}
-
-#
-# setup brew (install taps, bottles, etc)
-#
-setup_brew() {
-  get_sudo
-  install_brew
-  update_brew
-  upgrade_formulae
-  install_taps
-  install_bottles
-  cleanup_brew
-}
-
-#
-# install rvm
-#
-setup_rvm() {
-  local rvm_rev="stable"
-  local rvm_url="https://get.rvm.io"
-  local rvm_exe="/Users/${USER}/.rvm/bin/rvm"
-
+  # install bottles
   (
-    cd "/Users/${USER}"
-    curl -sSL "${rvm_url}" | bash -s "${rvm_rev}"
+    for bottle in "${brew_bottles[@]}"
+    do
+      brew_action "install" "${bottle}"
+    done
   )
+
+  write_log "${FUNCNAME[0]} => done"
 }
 
 #
 # setup: entry point
 #
 main() {
-  setup_brew
-  setup_go
-  setup_rvm
-}
+  write_log "${FUNCNAME[0]} => init"
 
+  # install & setup brew
+  brew_install
+  brew_action "upgrade"
+
+  # install bottles
+  brew_install_bottles
+
+  # cleanup install of brew
+  brew_action "update"
+  brew_action "prune"
+  brew_action "cleanup"
+
+  write_log "${FUNCNAME[0]} => done"
+}
 main
