add the 'gogo' function and change go path

diff --git a/etc/zshrc b/etc/zshrc
--- a/etc/zshrc
+++ b/etc/zshrc
@@ -35,7 +35,7 @@ alias lsd="ls -lphG | grep '^d'"
 # zsh: exports
 #
 export LANG="en_US.UTF-8";
-export GOPATH="${HOME}/go"
+export GOPATH="${HOME}/source/golang"
 export GOROOT=/usr/local/go
 export EDITOR=/usr/local/bin/vim;
 export PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/local/bin:${PATH}"
@@ -53,4 +53,19 @@ tre () {
 
 vssh () {
   cd ~/source/vagrant && vagrant ssh -c 'sudo su -' "$@"
+}
+
+gogo(){
+	local pkg=$1
+
+	# search for the project dir in the GOPATH
+  local path=( `find "${GOPATH}/src" -type d -iname "${pkg}"` )
+
+	if [[ "${path}" == "" ]]; then
+		echo "Could not find a directory named ${pkg} in ${GOPATH}"
+		echo "Maybe you need to 'go get' it ;)"
+		return 1
+	fi
+
+	cd "${path}" || return 1
 }
